### ISSUE TITLE
영화관 정보 가져올때 key에러 발생

### ISSUE THREAD

**Issue by jiho5993** [jiho5993/movchatbot#3]
<img width="468" alt="스크린샷 2022-03-22 오후 5 39 45" src="https://user-images.githubusercontent.com/42717320/159440773-c72d5178-c08d-4d60-a8d4-b68cf495764d.png">
인풋이 위와 같을때 <br/><br/>

<img width="844" alt="스크린샷 2022-03-22 오후 5 40 09" src="https://user-images.githubusercontent.com/42717320/159440848-084c8276-a667-4c29-9fb8-ee692d095dab.png">
위와 같은 key error가 발생한다.
<br/><br/>
아마 예외처리가 되지 않았다고 생각함

**Comment by siroch** [comment]
휴업중인 지점들을 처리할 수 있는 내용 추가 완료
