### ISSUE TITLE
영화관 위치 에러 (가는길 찾기)

### ISSUE THREAD

**Issue by jiho5993** [jiho5993/movchatbot#4]
![스크린샷 2022-03-23 오전 12 20 19](https://user-images.githubusercontent.com/42717320/159516583-d5777206-bdc0-483a-9513-0a82ed1ece5f.png)
위 두곳은 인계동, 매산로로 각각 다른 위치에 표시되어야하는데 둘 다 같은 곳을 보고 있음

**Comment by siroch** [comment]
해결완료
